#pragma once

#define LSM_TOTAL_MEM_SIZE_LIMIT (64 * 1024 * 1024) // 64MB
#define LSM_PER_MEM_SIZE_LIMIT (1024 * 1024 * 1024) // 4MB

#define LSM_BLOCK_MEM_LIMIT (32 * 1024) // 32KB

#define LSM_BLOCK_CACHE_CAPACITY 1024
#define LSM_BLOCK_CACHE_K 8

#define BLOOM_FILTER_EXPEXTED_SIZE 65536
#define BLOOM_FILTER_EXPEXTED_ERROR_RATE 0.1

#define REDIS_EXPIRE_HEADER "RESDIS_EXPIRE_HEADER_"
#define REDIS_HASH_HEADER "REDIS_HASH_HEADER_"
#define REDIS_HASH_VALUE_PREFIX "REDIS_HEAD_VALUE_PREFIX_"

#define REDIS_SORTED_SET_PREFIX "REDIS_SORTED_SET_PREFIX_"
#define REDIS_SORTED_SET_SCORE_LEN 32

#define REDIS_SET_PREFIX "REDIS_SET_PREFIX_"
#define REDIS_FILED_SEPARATOR '$'